version: '3.8'
services:
  fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./sock:/var/run/php-fpm
    links:
      - mysql
    networks:
      - default
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
      - ${APP_HTTPS_PORT:-443}:443
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./sock:/var/run/php-fpm
      - ./log/nginx:/var/log/nginx
      - /etc/ssl:/etc/ssl
    networks:
      - default

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-123789}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-123789}
      - MYSQL_DATABASE=${DB_NAME:-db}
    volumes:
      - ../db:/var/lib/mysql

      - ./custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
    volumes:
      - ./tmp:/tmp
volumes:
  sock: null
networks:
  default: null
